"Resource/UI/BottomSpectatorGUI.res"
{
	"bottombar"
	{
		"ControlName"		"Frame"
		"fieldName"			"bottombar"
		"tall"				"40"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"0"
	}
	"settingscombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"settingscombo"
		"xpos"				"15"
		"ypos"				"16"
		"wide"				"160"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"0"
		"textAlignment"		"west"
	}
	"playercombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"playercombo"
		"xpos"				"c-200"
		"ypos"				"16"
		"wide"				"360"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"1"
		"textAlignment"		"center"
	}
	"viewcombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"viewcombo"
		"xpos"				"r200"
		"ypos"				"16"
		"wide"				"160"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"0"
		"textAlignment"		"west"
	}
	"playerprev"
	{
		"ControlName"		"Button"
		"fieldName"			"playerprev"
		"xpos"				"c-225"
		"ypos"				"16"
		"wide"				"18"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"command"			"playerprev"
	}
	"playernext"
	{
		"ControlName"		"Button"
		"fieldName"			"playernext"
		"xpos"				"c175"
		"ypos"				"16"
		"wide"				"18"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"command"			"playernext"
	}

}
