"Resource/UI/SpectatorGUI.res"
{
	"SpectatorGUI"
	{
		"ControlName"	"Frame"
		"fieldName"		"SpectatorGUI"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}
	"TopBar"
	{
		"ControlName"	"Panel"
		"fieldName"		"TopBar"
		"xpos"			"0"
		"ypos"			"0"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
	}
	"BottomBar"
	{
		"ControlName"		"Frame"
		"fieldName"			"BottomBar"
		"xpos"				"0"
		"ypos"				"r40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"0"
	}
	"bottombarblank"
	{
		"ControlName"		"Panel"
		"fieldName"			"bottombarblank"
		"xpos"				"0"
		"ypos"				"r40"
		"tall"				"40"	// this needs to match the size of BottomBar
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"0"
		"paintbackground"	"0"
	}
	"FooterBar"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"FooterBar"
		"xpos"				"-1000"
		"ypos"				"-1000"
		"wide"				"1000"
		"tall"				"40"	// change this number to adjust the height of the bottom bar. then change the "ypos" value to the same number and add an 'r' before the value (ie. "tall" "44" => "ypos" "-1000")
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"0"
		"fillcolor"			"0 0 0 128"
		"labelText"			""
		"textAlignment"		"west"
	}
	"playerlabel"
	{
		"ControlName"		"Label"
		"fieldName"			"playerlabel"
		"xpos"				"-1000"	// original c-108
		"ypos"				"-1000"	// original 441
		"wide"				"350"	// original 216
		"tall"				"36"    // original 40
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"	// original 0
		"enabled"			"0"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"paintbackground"	"0"
	}
	"Following"
    {
        "ControlName"		"Label"
        "fieldName"			"joinClass"
        "xpos"				"-1000"
        "ypos"				"-1000"
        "wide"				"500"
        "tall"				"18"
        "autoResize"		"0"
        "pinCorner"			"0"
        "visible"			"0"
        "enabled"			"0"
        "tabPosition"		"0"
        "labelText"			"FOLLOWING"
        "textAlignment"		"left" // west
        "dulltext"	    	"0"
        "brighttext"		"0"
        "font"	        	"DefaultSmall"
        "wrap"	        	"0"
        "paintbackground"	"0"
    }
	"CTScoreValue"
	{
		"ControlName"	"Label"
		"fieldName"		"CTScoreValue"
		"xpos"			"-1000"
		"ypos"			"-1000"
		"wide"			"14"
		"tall"			"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"TERScoreValue"
	{
		"ControlName"	"Label"
		"fieldName"		"TERScoreValue"
		"xpos"			"c-110"
		"ypos"			"20"
		"wide"			"14"
		"tall"			"14"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"timerimage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"timerimage"
		"xpos"			"c-32"
		"ypos"			"8"
		"wide"			"16"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/timer"
		"scaleImage"	"1"
	}
	"timerlabel"
	{
		"ControlName"	"Label"
		"fieldName"		"timerlabel"
		"xpos"			"c-8"
		"ypos"			"8"
		"wide"			"70"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"00:00"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"extrainfo"
	{
		"ControlName"	"Label"
		"fieldName"		"extrainfo"
		"xpos"			"r56"
		"ypos"			"12"
		"wide"			"44"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"Spectators"
	{
		"ControlName"	"Label"
		"fieldName"		"joinClass"
		"xpos"			"r480"
		"ypos"			"445"
		"wide"			"100"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Spectators"
		"textAlignment"	"center"
		"dulltext"		"1"
		"brighttext"	"0"
		"font"			"DefaultSmall"
		"wrap"			"0"
	}
	"TSeparator"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"TSeparator"
		"xpos"			"-1000"
		"ypos"			"-1000"
		"wide"			"4"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
		"fillcolor"		"team1"
		"labelText"		""
		"textAlignment"	"west"
	}
	"CTSeparator"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"CTSeparator"
		"xpos"			"-1000"
		"ypos"			"-1000"
		"wide"			"4"
		"tall"			"40"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
		"fillcolor"		"team2"
		"labelText"		""
		"textAlignment"	"west"
	}
}
