name: Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup MSVC (x86)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Config
        run: cmake -B build -G "Visual Studio 17 2022" -A Win32 -T v142

      - name: Build
        run: cmake --build build --config Release

      - name: Upload DLL
        uses: actions/upload-artifact@v7
        with:
          name: onepointsix_broadcast
          path: build/Release/*.dll

  release:
    needs: build
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.cz.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: onepointsix_broadcast
          path: artifacts

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Prepare release bundle
        run: |
          VERSION=v${{ env.REVISION }}

          mkdir -p dist/cstrike/resource/UI

          cp artifacts/onepointsix_broadcast.dll dist/onepointsix_broadcast/
          cp cstrike/resource/UI/BottomSpectator.res dist/cstrike/resource/UI/
          cp cstrike/resource/UI/ScoreBoard.res dist/cstrike/resource/UI/
          cp cstrike/resource/UI/Spectator.res dist/cstrike/resource/UI/
          cp cstrike/resource/ClientScheme.res dist/cstrike/resource/
          cp cstrike/b_720.cfg dist/cstrike/
          cp cstrike/sprites.txt dist/onepointsix_broadcast/
          cp README.md dist/
          cd dist

          zip -r ../onepointsix_broadcast-${VERSION}.zip .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          tag_name: v${{ env.REVISION }}
          files: |
            onepointsix_broadcast-v${{ env.REVISION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
